import type { Metadata } from "next";
import "./globals.css";
import { FormProvider } from "@/context/FormContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning suppressContentEditableWarning>
      <body className={`m-0 p-0`}>
        <FormProvider>{children}</FormProvider>
      </body>
    </html>
  );
}
